# Generated by Django 4.0.6 on 2022-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_Description', models.CharField(max_length=5000)),
                ('service_price', models.CharField(max_length=30)),
                ('service_category', models.CharField(max_length=50)),
            ],
        ),
    ]
