# Generated by Django 4.0.6 on 2022-08-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samandas_salon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_Description',
            new_name='service_description',
        ),
    ]
